version: "3.8"
   
services:
    django:
        build: .
        container_name: djangocontainer
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - redis
    celery:
        build: .
        command: celery -A basicdjango worker -l INFO
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - django
            - redis  
    flower:
        image: mher/flower:0.9.7
        command: ['flower', '--broker=redis://redis:6379', '--port=5555']
        ports:
            - 5557:5555
        depends_on:
            - redis
    redis:
        image: "redis:alpine"

        

